Learning/urls.py
from django.urls import path,include
from .views import *
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth.decorators import login_required



urlpatterns = [
    path('',home,name='home'),
    path('learning/',Learning,name='Learning'),
    path('logout/', exit, name='exit'),
    path('veruser/', datosus, name='see_users'),
    path('Register/', register, name='register'),
    path('ResetPassword/<int:pk>/',Cambiar_contraseña,name='reset_password'),
    path('editaruser/<int:pk>/', editaruser, name='edit_user'),
    path('delete/<int:pk>/',delete_user,name='delete_user'),

#This are the profiles urls 
    path('users/me/profile/',update_profile,name='update_profile'),
    path('users/<str:username>/',UserDetailView.as_view(),name='detail'),
    path('staff/overview/',profile,name='staff_overview'),
    path('learning/overview/', login_required(ProfileView.as_view()), name='learning_overview'),
    path('cohorte/<int:cohorte_id>/estudiantes/', estudiantes_inscritos, name='estudiantes_inscritos'),

#This are the Curses urls
    path('cursos/',login_required(CoursesView.as_view()), name='cursos'),
    path('crear/curso/',crear_curso,name='crear_curso'),
    path('curso/<int:pk>/edit/',login_required(CourseEditView.as_view()),name='editar_curso'),
    path('curso/<int:pk>/delete',login_required(CourseDeleteView.as_view()),name='borrar_curso'),
    path('error/',login_required(ErrorView.as_view()),name='error'),
    path('enroll_course/<int:course_id>/', CourseEnrollmentView.as_view(), name='enroll_course'),
    
    

#This include all the Urls of the app Task 
    path('tasks/',include(('Task.urls','Task'),namespace='tasks')),

    
#urls donde le profesor mirara los estudiantes inscritos a su curso
    path('cohorte/<int:cohorte_id>/estudiantes/', estudiantes_inscritos, name='estudiantes_inscritos'),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LearningYou2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('Learning.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reset/password_reset', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('reset/password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/password_reset_confirm/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Learning.views.error_404'

Task/urls.py
"""Task Urls."""

# Django

from django.urls import path

# Views
from Task.views import TaskCreationView
from Task import views

urlpatterns = [
    path(route='',
         view=views.tasks, 
         name='tasks'
         ),

    path(route='tasks_completed/',
         view=views.tasks_completed, 
         name='task_completed'
         ),

     path(route='create/',
         view=views.create_task,
         name='create_task'
         ),

    path(route='create/<int:course_id>/',
         view=TaskCreationView.as_view(),
         name='create_task_with_course'
         ),

    #<int:task_id>: significa que es un dato id entero,y se enviara al task_detail
    path(route='calificar_tarea/',
         view=views.calificar_tarea, 
         name='calificar_tarea'
         ),

    path(route='create_nota/',
         view=views.create_nota,
         name='create_nota'
         ),

    path(route='nota/',
         view=views.nota, 
         name='notas'
         ),

   path('lista_notas/', views.lista_notas, name='lista_notas'),


    path(route='<int:task_id>/nota_detail/',
         view=views.nota_detail, 
         name='nota_detail'
         ),

    path(route='<int:task_id>/complete/',
         view=views.complete_task,
         name='complete_task'
         ),

    path(route='<int:task_id>/delete/',
         view=views.delete_task,
         name='delete_task'
         ), 

    path(route='<int:task_id>/',
         view=views.task_detail,
         name='task_detail'
         ),

    path(route='notas/<int:nota_id>/',
         view=views.nota_detail, 
         name='nota_detail'
         ),

    path(route='notas/<int:nota_id>/complete/',
         view=views.complete_nota, 
         name='complete_nota'
         ),

    path(route='notas/<int:nota_id>/delete/',
         view=views.delete_nota, 
         name='delete_nota'
         ),
     path(route='complete/',
          view=views.tasks_completed2,
          name='task_completed'),
     
     path('complete/', views.tasks_completed2, name='task_completed_2'),
     path('nota/', views.nota, name='notas'),
    
]

Learning/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser, AbstractBaseUser,PermissionsMixin,User


class User(AbstractUser,AbstractBaseUser,PermissionsMixin):
    cedula = models.CharField(max_length=11,unique=True, verbose_name='Cedula',blank=True, help_text=(
        "Obligatorio. Digite su nemero de Cedula completo. Unicamente numeros. Sin puntos ni comas"
    ))
    phone = models.CharField(max_length=10, verbose_name='Celuar', blank=False, help_text=(
        "Obligatorio. Digite su nemero de Celular completo. Unicamente numeros. Sin puntos ni comas"
    ))
    is_profesor = models.BooleanField(
        ("Rol Profesor"),
        default=False
    )
    is_Estudiante = models.BooleanField(
        ("Estudiante"),
        default=False
    )

class Cohorte(models.Model):
    STATUS_CHOICES = (
        ('I', 'Inscripciónes Abiertas'),
        ('P', 'En Progreso'),
        ('F', 'Finalizado'),
    )
    nombreCoh = models.CharField(max_length=100)
    descrptionCoh = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    delted = models.DateTimeField(null=True,blank=True)
    teacher  = models.ForeignKey(User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        limit_choices_to=Q(is_profesor=True)
        )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='I', verbose_name='Estado')
    def codCoh(self):
        return "{} ".format(self.nombreCoh)
    
    def __str__(self):
        return self.codCoh()

class Registration(models.Model):
    course = models.ForeignKey(Cohorte, 
        on_delete=models.CASCADE,
        verbose_name='Curso'
        )
    student = models.ForeignKey(User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='students_registration',
        limit_choices_to=Q(is_Estudiante=True),
        verbose_name='Estudiante'
        )
    def __str__(self):
        return f'{self.student.username} - {self.course.nombreCoh}'
    class Meta:
        verbose_name = 'Inscripcion'
        verbose_name_plural = 'Inscripciones'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    biography = models.TextField(blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username










"""
class Cursos(models.Model):
    nombre = models.CharField(max_length=100)
    description = models.TextField(blank=True,max_length=500)
    students = models.ForeignKey(User, on_delete=models.CASCADE,
        null=True,
        blank=True,
        limit_choices_to=Q(is_Estudiante=True)
        )
    lecciones = models.ForeignKey(Cohorte,on_delete=models.CASCADE,null= True,blank=True)
"""

Learning/forms.py
from django import forms
from .models import User,Cohorte
from django.contrib.auth.forms import UserCreationForm


class CustumUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','cedula','phone','username','password1', 'password2','is_staff','is_profesor','is_Estudiante']
        labels = {
            'first_name': 'Nombre',
            'last_name':'Apellidos',
            'cedula':'Cedula',
            'phone': 'Phone',
            'username': 'Nombre De Usuario',
            'password1':'Contraseña',
            'password2':'Repetir Contraseña',
            'is_staff': 'is Admin ?',
            'is_profesor': 'is a Teacher ?',
            'is_Estudiante': 'is a Student ?',
        }
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca sus Nombres'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Last Name'}),
            'cedula':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca su Cedula'}),
            'phone':forms.TextInput(attrs={'class':'form-control','placeholder':'Contact number'}),
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca su Nombre de Usuario'}),
            'password1':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Indroduzca su Contraseña'}),
            'password2':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Repita su Contraseña'}),
            'is_staff':forms.CheckboxInput(),
            'is_profesor':forms.CheckboxInput(),
            'is_Estudiante':forms.CheckboxInput(),
        }

class editarUser (forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'cedula', 'phone', 'is_staff', 'is_profesor', 'is_Estudiante']

    def clean_email(self):
        email_field = self.cleaned_data['email']
        if User.objects.filter(email=email_field).exists():
            raise forms.ValidationError('Este correo electronico ya esta registrado')
        return email_field
            
class ChangePasswordForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['password1','password2']

class CursoForm(forms.ModelForm):
    descrptionCoh = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), label='Descripción')
    class Meta:
        model = Cohorte
        fields = ['nombreCoh','descrptionCoh','teacher','status']

    """estudiantes = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(is_Estudiante=True),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )"""

class ProfileForm(forms.Form):
    """Profile form."""
    biography = forms.CharField(max_length=500,required=False)
    address = forms.CharField(max_length=100,required=False)
    picture = forms.ImageField()

Learning/templates/Cohortes/cohortes.html
{% extends "base.html" %}
{% block title %} | Cursos |{% endblock  %}
{% block content %}
<div>

</div>
<br>
<div class="container my-4">
  <div class="row">
      <div class="col">
          <h2>Nuestros Cursos</h2>
      </div>
      <div class="col">
          <span class="float-end">
              {% if request.user.is_staff %}
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'crear_curso' %}" class="btn btn-primary" role="button">
                    <i class="bi bi-plus-circle "></i> Agregar Curso</a>
              </div>
              {% endif %}
          </span>
      </div>
  </div>

  <hr>

  <!-- sección de mensajes -->
  {% if messages %}
      <div class="container mt-3">
          {% for message in messages %}
              <div class="alert alert-success" role="alert">
                  {{ message }}
              </div>
          {% endfor %}
      </div>
  {% endif %}

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 my-4">
      {% for course in courses %}
          <div class="col">
              <div class="card">
                  <div class="card-body border rounded shadow-lg">
                      <h5 class="card-title">{{ course.nombreCoh }}</h5>
                      <p class="card-text">{{ course.descrptionCoh }}</p>
                      {% if request.user.is_profesor %} 
                      <p class="card-text">
                          <strong>Profesor: </strong>{{ course.teacher.first_name }} {{ course.teacher.last_name }}
                      </p>
                      <p class="card-text"><strong>Cantidad de inscritos: </strong>{{ course.enrollment_count }}
                      </p>
                     <!--  <a href="{% url 'tasks:create_nota' %}">Crear Nota
                                {{ course.enrollment_count }}
                            </a>--> 
                            {% endif %}

                      {% if course.status == 'F' %}
                          <h5><span class="badge bg-danger w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'P' %}
                          <h5><span
                              class="badge bg-warning text-dark w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'I' %}
                          <h5><span class="badge bg-success w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if request.user.is_Estudiante and not course.is_enrolled %}
                              <a class="btn btn-sm btn-success" href="{% url 'enroll_course' course.id %}">Anotarse</a>
                          {% elif course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a> 
                              <a class="btn btn-sm btn-primary" href="{% url 'Task:create_task' %}">Ir a crear tarea</a> 
                              <a class="btn btn-sm btn-primary" href="{% url 'tasks:lista_notas' %}">ver  Nota</a> 
                              
                          {% endif %}
                      {% endif %}

                      {% if request.user.is_staff %}
                          <a class="btn btn-sm btn-warning" href="{% url 'editar_curso' course.id %}">Editar</a>
                          <a class="btn btn-sm btn-danger" href="{% url 'borrar_curso' course.id %}">Eliminar</a>
                      {% endif %}
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>
{% endblock  %}

Learning/templates/Cohortes/crear_curso.html
{% extends "base.html" %}
{% block title %} Create a Course{% endblock  %}
{% block content %} 
{% load crispy_forms_tags %}
<div class="container my-4">
    <div class="row">
        <div class="col">
            <h2>Create a Course</h2>
        </div>
        <div class="col">
            <span class="float-end">
                {% if request.user.is_staff %}
                <div class="mb-2" class="fixed-top">
                  <a href="{% url 'cursos' %}" class="btn btn-success" role="button">
                    <i class="bi bi-box-arrow-left"></i> Courses </a>
                </div>
                {% endif %}
            </span>
        </div>
    </div>
    <!-- sección de mensajes -->
    {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <div class="card mx-auto my-5" style="width: 40rem;">
            <div class="card-body border rounded shadow-lg">
                <h5 class="card-title">Complete all fields</h5>
                {{ form | crispy }}
                <a class="card-link" href="{% url 'home' %}">HOME</a>

                <button class="btn btn-primary float-end" type="submit">Save</button>
            </div>
        </div>
    </form>
    <br>
    <hr>
</div>
{% endblock %}

Learning/templates/Cohortes/cursos.html
{% extends "base.html" %}
{% block title %} | Cursos |{% endblock  %}
{% block content %}
<div>

</div>
<br>
<div class="container my-4">
  <div class="row">
      <div class="col">
          <h2>Nuestros Cursos</h2>
      </div>
      <div class="col">
          <span class="float-end">
              {% if request.user.is_staff %}
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'crear_curso' %}" class="btn btn-primary" role="button">
                    <i class="bi bi-plus-circle "></i> Agregar Curso</a>
              </div>
              {% endif %}
          </span>
      </div>
  </div>

  <hr>

  <!-- sección de mensajes -->
  {% if messages %}
      <div class="container mt-3">
          {% for message in messages %}
              <div class="alert alert-success" role="alert">
                  {{ message }}
              </div>
          {% endfor %}
      </div>
  {% endif %}

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 my-4">
      {% for course in courses %}
          <div class="col">
              <div class="card">
                  <div class="card-body border rounded shadow-lg">
                      <h5 class="card-title">{{ course.nombreCoh }}</h5>
                      <p class="card-text">{{ course.descrptionCoh }}</p>
                      {% if request.user.is_profesor %} 
                      <p class="card-text">
                          <strong>Profesor: </strong>{{ course.teacher.first_name }} {{ course.teacher.last_name }}
                      </p>
                      <p class="card-text"><strong>Cantidad de inscritos: </strong>{{ course.enrollment_count }}
                      </p>
                     <!--  <a href="{% url 'tasks:create_nota' %}">Crear Nota
                                {{ course.enrollment_count }}
                            </a>--> 
                            {% endif %}

                      {% if course.status == 'F' %}
                          <h5><span class="badge bg-danger w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'P' %}
                          <h5><span
                              class="badge bg-warning text-dark w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'I' %}
                          <h5><span class="badge bg-success w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if request.user.is_Estudiante and not course.is_enrolled %}
                              <a class="btn btn-sm btn-success" href="{% url 'enroll_course' course.id %}">Anotarse</a>
                          {% elif course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a> 
                              <a class="btn btn-sm btn-primary" href="{% url 'tasks:create_task' %}">Ir a crear tarea</a> 
                              <a class="btn btn-sm btn-primary" href="{% url 'tasks:lista_notas' %}">ver  Nota</a> 
                              
                          {% endif %}
                      {% endif %}

                      {% if request.user.is_staff %}
                          <a class="btn btn-sm btn-warning" href="{% url 'editar_curso' course.id %}">Editar</a>
                          <a class="btn btn-sm btn-danger" href="{% url 'borrar_curso' course.id %}">Eliminar</a>
                      {% endif %}
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>
{% endblock  %}

Learning/templates/Cohortes/delete_curso.html
{% extends 'base.html' %}
{% block Title %}
| Delete Course |
{% endblock  %}

{% block content %}
    <div class="container my-4">
        <div class="row">
            <div class="col">
                <h2>Delete Courses</h2>
            </div>
            <div class="col">
                <span class="float-end">
                    {% if request.user.is_staff %}
                    <div class="mb-2" class="fixed-top">
                      <a href="{% url 'cursos' %}" class="btn btn-success" role="button">
                        <i class="bi bi-box-arrow-left"></i> Courses </a>
                    </div>
                    {% endif %}
                </span>
            </div>
        </div>
        <br>
        <hr>
        <form method="post">
            {% csrf_token %}
            <div class="card w-50 mx-auto my-5">
                <div class="card-body">
                    <h5 class="card-title">Irreversible course elimination process</h5>
                    
                    <p>Are you sure you want to delete the course <strong>{{ course.nombreCoh }}</strong> ?</p>
                    
                    <div class="float-end">
                        <a type="button" class="btn btn-danger mt-auto" href="" data-bs-toggle="modal"
                           data-bs-target="#deleteModal">Delete</a>
                        <a class="btn btn-secondary mt-auto" href="{% url 'cursos' %}">Cancel</a>
                    </div>
                </div>
            </div>

            <!-- MODAL PARA CONFIRMAR LA ELIMINACION DEL REGISTRO -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirm the delete</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this course? (This action can not be undone)
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-danger">Delete Course</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
{% endblock %}

Learning/templates/Cohortes/edit_curso.html
{% extends "base.html" %}
{% block title %} Edit Course{% endblock  %}
{% block content %} 
{% load crispy_forms_tags %}
<div class="container my-4">
    <div class="row">
        <div class="col">
            <h2>Edit Courses</h2>
        </div>
        <div class="col">
            <span class="float-end">
                {% if request.user.is_staff %}
                <div class="mb-2" class="fixed-top">
                  <a href="{% url 'cursos' %}" class="btn btn-success" role="button">
                    <i class="bi bi-box-arrow-left"></i> Courses </a>
                </div>
                {% endif %}
            </span>
        </div>
    </div>
    <!-- sección de mensajes -->
    {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <div class="card mx-auto my-5" style="width: 40rem;">
            <div class="card-body border rounded shadow-lg">
                <h5 class="card-title">Complete all fields to edit the course</h5>
                {{ form | crispy }}
                <a class="card-link" href="{% url 'home' %}">HOME</a>
                <button class="btn btn-primary float-end" type="submit">Save Changes</button>
            </div>
        </div>
    </form>
    <br>
    <hr>
</div>
{% endblock %}