Learning/urls.py
from django.urls import path,include
from .views import *
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth.decorators import login_required



urlpatterns = [
    path('',home,name='home'),
    path('learning/',Learning,name='Learning'),
    path('logout/', exit, name='exit'),
    path('veruser/', datosus, name='see_users'),
    path('Register/', register, name='register'),
    path('ResetPassword/<int:pk>/',Cambiar_contraseña,name='reset_password'),
    path('editaruser/<int:pk>/', editaruser, name='edit_user'),
    path('delete/<int:pk>/',delete_user,name='delete_user'),

#This are the profiles urls 
    path('users/me/profile/',update_profile,name='update_profile'),
    path('users/<str:username>/',UserDetailView.as_view(),name='detail'),
    path('staff/overview/',profile,name='staff_overview'),
    path('learning/overview/', login_required(ProfileView.as_view()), name='learning_overview'),
    path('cohorte/<int:cohorte_id>/estudiantes/', estudiantes_inscritos, name='estudiantes_inscritos'),

#This are the Curses urls
    path('cursos/',login_required(CoursesView.as_view()), name='cursos'),
    path('crear/curso/',crear_curso,name='crear_curso'),
    path('curso/<int:pk>/edit/',login_required(CourseEditView.as_view()),name='editar_curso'),
    path('curso/<int:pk>/delete',login_required(CourseDeleteView.as_view()),name='borrar_curso'),
    path('error/',login_required(ErrorView.as_view()),name='error'),
    path('enroll_course/<int:course_id>/', CourseEnrollmentView.as_view(), name='enroll_course'),
    
    

#This include all the Urls of the app Task 
    path('tasks/',include(('Task.urls','Task'),namespace='tasks')),

    
#urls donde le profesor mirara los estudiantes inscritos a su curso
    path('cohorte/<int:cohorte_id>/estudiantes/', estudiantes_inscritos, name='estudiantes_inscritos'),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LearningYou2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('Learning.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reset/password_reset', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('reset/password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/password_reset_confirm/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Learning.views.error_404'

Task/urls.py
"""Task Urls."""

# Django

from django.urls import path

# Views
from Task.views import TaskCreationView
from Task import views

urlpatterns = [
    path(route='',
         view=views.tasks, 
         name='tasks'
         ),

    path(route='tasks_completed/',
         view=views.tasks_completed, 
         name='task_completed'
         ),

     path(route='create/',
         view=views.create_task,
         name='create_task'
         ),

    path(route='create/<int:course_id>/',
         view=TaskCreationView.as_view(),
         name='create_task_with_course'
         ),

    #<int:task_id>: significa que es un dato id entero,y se enviara al task_detail
    path(route='calificar_tarea/',
         view=views.calificar_tarea, 
         name='calificar_tarea'
         ),

    path(route='create_nota/',
         view=views.create_nota,
         name='create_nota'
         ),

    path(route='nota/',
         view=views.nota, 
         name='notas'
         ),

   path('lista_notas/', views.lista_notas, name='lista_notas'),


    path(route='<int:task_id>/nota_detail/',
         view=views.nota_detail, 
         name='nota_detail'
         ),

    path(route='<int:task_id>/complete/',
         view=views.complete_task,
         name='complete_task'
         ),

    path(route='<int:task_id>/delete/',
         view=views.delete_task,
         name='delete_task'
         ), 

    path(route='<int:task_id>/',
         view=views.task_detail,
         name='task_detail'
         ),

    path(route='notas/<int:nota_id>/',
         view=views.nota_detail, 
         name='nota_detail'
         ),

    path(route='notas/<int:nota_id>/complete/',
         view=views.complete_nota, 
         name='complete_nota'
         ),

    path(route='notas/<int:nota_id>/delete/',
         view=views.delete_nota, 
         name='delete_nota'
         ),
     path(route='complete/',
          view=views.tasks_completed2,
          name='task_completed'),
     
     path('complete/', views.tasks_completed2, name='task_completed_2'),
     path('nota/', views.nota, name='notas'),
    
]

Learning/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser, AbstractBaseUser,PermissionsMixin,User


class User(AbstractUser,AbstractBaseUser,PermissionsMixin):
    cedula = models.CharField(max_length=11,unique=True, verbose_name='Cedula',blank=True, help_text=(
        "Obligatorio. Digite su nemero de Cedula completo. Unicamente numeros. Sin puntos ni comas"
    ))
    phone = models.CharField(max_length=10, verbose_name='Celuar', blank=False, help_text=(
        "Obligatorio. Digite su nemero de Celular completo. Unicamente numeros. Sin puntos ni comas"
    ))
    is_profesor = models.BooleanField(
        ("Rol Profesor"),
        default=False
    )
    is_Estudiante = models.BooleanField(
        ("Estudiante"),
        default=False
    )

class Cohorte(models.Model):
    STATUS_CHOICES = (
        ('I', 'Inscripciónes Abiertas'),
        ('P', 'En Progreso'),
        ('F', 'Finalizado'),
    )
    nombreCoh = models.CharField(max_length=100)
    descrptionCoh = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    delted = models.DateTimeField(null=True,blank=True)
    teacher  = models.ForeignKey(User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        limit_choices_to=Q(is_profesor=True)
        )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='I', verbose_name='Estado')
    def codCoh(self):
        return "{} ".format(self.nombreCoh)
    
    def __str__(self):
        return self.codCoh()

class Registration(models.Model):
    course = models.ForeignKey(Cohorte, 
        on_delete=models.CASCADE,
        verbose_name='Curso'
        )
    student = models.ForeignKey(User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='students_registration',
        limit_choices_to=Q(is_Estudiante=True),
        verbose_name='Estudiante'
        )
    def __str__(self):
        return f'{self.student.username} - {self.course.nombreCoh}'
    class Meta:
        verbose_name = 'Inscripcion'
        verbose_name_plural = 'Inscripciones'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    biography = models.TextField(blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username










"""
class Cursos(models.Model):
    nombre = models.CharField(max_length=100)
    description = models.TextField(blank=True,max_length=500)
    students = models.ForeignKey(User, on_delete=models.CASCADE,
        null=True,
        blank=True,
        limit_choices_to=Q(is_Estudiante=True)
        )
    lecciones = models.ForeignKey(Cohorte,on_delete=models.CASCADE,null= True,blank=True)
"""

Task/models.py
"""Task Models"""

#DJANGO
from django.db import models
from django.db.models import Q
#APP leaning
from Learning.models import User,Cohorte,Registration


class Task(models.Model):
    #aca creara la tabla
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    field = models.FileField(upload_to='archivos_adjuntos',blank=True, null=True)
    #blanck y null,permite qye estos campos puedan estar vacios en el formulario
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important= models.BooleanField(default=False)
    #si se elimina un dato de user,todo lo q tenga q ver con ese usuario se eliminara en cascada
    curso = models.ForeignKey(Cohorte,on_delete=models.CASCADE ,blank=True,null=True)
    def __str__(self):
     return f"{self.title} by {self.curso}"
   #se concardena el titulo de la tarea y el usuario que la envia



class Calificacion(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE,
        null=True,
        blank=True,
        limit_choices_to=Q(is_Estudiante=True)
        )
    tareas= models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)
    mark1 = models.PositiveIntegerField(null=True, blank=True, verbose_name='nota1')
    mark2 = models.PositiveIntegerField(null=True, blank=True, verbose_name='nota2')
    mark3 = models.PositiveIntegerField(null=True, blank=True, verbose_name='nota3')
    average = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name='promedio')
    
    def __str__(self):
        return f"Calificación de {self.student.username}"

    
    #calcular rl promedio llamando a la funcion
    def calculate_average(self):
        marks = [self.mark1, self.mark2, self.mark3]
        valid_marks = [mark for mark in marks if mark is not None]
        if valid_marks:
            return sum(valid_marks) / len(valid_marks)
        return None
    
    def save(self, *args, **kwargs):
        if self.mark1 or self.mark2 or self.mark3:
            self.average = self.calculate_average()
        super().save(*args, **kwargs)
        
    class Meta:
        verbose_name ='nota'
        verbose_name_plural='notas'

Learning/forms.py
from django import forms
from .models import User,Cohorte
from django.contrib.auth.forms import UserCreationForm


class CustumUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','cedula','phone','username','password1', 'password2','is_staff','is_profesor','is_Estudiante']
        labels = {
            'first_name': 'Nombre',
            'last_name':'Apellidos',
            'cedula':'Cedula',
            'phone': 'Phone',
            'username': 'Nombre De Usuario',
            'password1':'Contraseña',
            'password2':'Repetir Contraseña',
            'is_staff': 'is Admin ?',
            'is_profesor': 'is a Teacher ?',
            'is_Estudiante': 'is a Student ?',
        }
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca sus Nombres'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Last Name'}),
            'cedula':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca su Cedula'}),
            'phone':forms.TextInput(attrs={'class':'form-control','placeholder':'Contact number'}),
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Indroduzca su Nombre de Usuario'}),
            'password1':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Indroduzca su Contraseña'}),
            'password2':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Repita su Contraseña'}),
            'is_staff':forms.CheckboxInput(),
            'is_profesor':forms.CheckboxInput(),
            'is_Estudiante':forms.CheckboxInput(),
        }

class editarUser (forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'cedula', 'phone', 'is_staff', 'is_profesor', 'is_Estudiante']

    def clean_email(self):
        email_field = self.cleaned_data['email']
        if User.objects.filter(email=email_field).exists():
            raise forms.ValidationError('Este correo electronico ya esta registrado')
        return email_field
            
class ChangePasswordForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['password1','password2']

class CursoForm(forms.ModelForm):
    descrptionCoh = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), label='Descripción')
    class Meta:
        model = Cohorte
        fields = ['nombreCoh','descrptionCoh','teacher','status']

    """estudiantes = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(is_Estudiante=True),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )"""

class ProfileForm(forms.Form):
    """Profile form."""
    biography = forms.CharField(max_length=500,required=False)
    address = forms.CharField(max_length=100,required=False)
    picture = forms.ImageField()

Task/forms.py
"""Task Urls"""
# Django
from django import forms

# Task Form
from .models import Task, Calificacion

class TaskForm(forms.ModelForm, ):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), label='Description')

    class Meta:
        model = Task
        fields = ['title', 'description','curso','field',]
        
    def _init_(self, *args, **kwargs):
        #este es el metodo constructor de la clase
        #init sirve para instanciar un objrto de una clase
        super(TaskForm, self)._init_(*args, **kwargs)
        self.fields['field'].widget = forms.ClearableFileInput(attrs={'multiple': False})
        #el clearblefileinput permite seleccionar varios archivos

class CalificacionForm(forms.ModelForm):
    class Meta:
        model = Calificacion
        fields = ['student','mark1','tareas']

Learning/templates/Task/create_nota.html
{% extends 'base.html' %}

{% block content %}

{{ error }}
<form action="/tasks/create_nota/" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {% load crispy_forms_tags %} <!-- Asegúrate de incluir esta línea -->
    {{ form | crispy }}
    <button type="submit">Subir Notas</button>
</form>
{% endblock %}

Learning/templates/Task/create_task.html
{% extends "base.html" %}

{% block title %}
    Crear Tarea
{% endblock  %}

{% block content %}
<div class="container my-4">
    <div class="form-container">
        <br>
        <div class="row">
            <div class="col">
                <h2>Crear tarea</h2>
            </div>
            <div class="col">
                <span class="float-end">
                    {% if request.user.is_staff %}
                    <div class="mb-2" class="fixed-top">
                      <a href="{% url 'tasks:tasks' %}" class="btn btn-secondary" role="button">
                        <i class="bi bi-box-arrow-left"></i> Tareas </a>
                    </div>
                    {% endif %}
                </span>
            </div>
        </div>
        <hr>

        <div class="row justify-content-md-center">
            <div class="col-6 p-4 border rounded shadow-lg" id="profile-box">
                <form action="/tasks/create/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="title">Titulo</label>
                        <input class="form-control" type="text" name="title" placeholder="title" value="{{ form.title.value }}">
                    </div>

                    <div class="form-group">
                        <label for="description">Descripcion</label>
                        <textarea class="form-control {% if form.description.errors %}is-invalid{% endif %}" name="description">
                            {% if form.errors %}{{ form.description.value }}{% else %}{{ task.description }}{% endif %}
                        </textarea>
                        <div class="invalid-feedback">
                            {% for error in form.description.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="course" class="col-form-label">Selecciona un curso:</label>
                        <select id="course" name="course" class="form-control">
                            {% for course in courses %}
                                <option value="{{ course.id }}">{{ course.nombreCoh }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="id_field">Archivo Adjunto:</label><br>
                        {{ form.field }}
                    </div>
                    
                    <br>

                        <button type="submit" class="btn btn-success">Crear tarea <i class="bi bi-journal-plus"></i></button>
                    
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}

Learning/templates/Task/lista_notas.html
{% extends "base.html" %}
{% block title %} | Cursos |{% endblock  %}
{% block content %}
<div class="container my-4">    
    <h1>Lista de Notas</h1>
    <div class="nota-container">
        <ul>
            {% for nota in notas %}
            <li>
                <div class="nota-info">
                    <div class="estudiante">
                        <span>Estudiante: {{ nota.student.username }}</span><br>
                    </div>
                    <div class="tarea">
                        <span class="tarea-title">Tarea:</span> {{ nota.tareas.title }}<br>
                    </div>
                    <div class="nota">
                        <span>Nota 1:</span> {{ nota.mark1 }}<br>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

Learning/templates/Task/nota_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Detalles de la Nota</h1>
<a href="{% url 'calificar_tarea' tarea.id %}">Calificar Tarea</a>
{{ error }}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>

<form action="{% url 'complete_nota' nota.id %}" method="POST">
    {% csrf_token %}
    <button type="submit">Completado</button>
</form>

<form action="{% url 'delete_nota' nota.id %}" method="POST">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
</form>
{% endblock %}


            
       
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

Learning/templates/Task/notas.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
    /* Estilos específicos para la lista de tareas pendientes */
    h1 {
        font-size: 24px; /* Tamaño del título */
        margin-bottom: 20px; /* Espacio inferior */
    }

    ul {
        list-style-type: none; /* Quita los puntos de la lista */
        padding: 0;
    }

    li {
        background-color: rgba(255, 255, 255, 0.8); /* Fondo del elemento con transparencia */
        border-radius: 10px; /* Bordes redondeados */
        padding: 20px; /* Espacio interno */
        margin-bottom: 20px; /* Espacio inferior entre elementos */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Sombra difuminada */
    }

    li:hover {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); /* Sombra más pronunciada al pasar el mouse */
    }

    a {
        text-decoration: none; /* Quita el subrayado de los enlaces */
        color: inherit; /* Hereda el color del texto */
    }
</style>
{% endblock %}

{% block content %}
<h1>tareas pendientes </h1>

<ul>
    <!--se recorrera por medio de un arreglo-->
    {% for task in tasks %}
    <!--tasks es el dato que se esta pasando desde el backend
    para cada elemento en el arreglo empieza a recorrerlo
    --> 
    <li>
        <a href="{% url 'notas_detail' task.id %}">
            <!--como es una variable dinámica se escribe de esa forma
            lo enviará al task detail con el parámetro task id, permitiendo buscar las tareas por su id -->
            {% if task.important %}
            <strong>{{nota.title}}</strong>
            {% else %}
            {{nota.title}}
            {% endif %}
            
            <p>{{nota.description}}</p>
            <p>{{nota.user.username}}</p>
            <p>Estudiante: {{ nota.student.username }}</p>


            
       
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

Learning/templates/Task/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-4">

        <div class="row">
            <div class="col">
                <h1>{{ task.title }}</h1>
            </div>
            <div class="col">
                <span class="float-end">
                    {% if request.user.is_staff %}
                    <div class="mb-2" class="fixed-top">
                        <a href="{% url 'tasks:tasks' %}" class="btn btn-secondary" role="button">
                          <i class="bi bi-box-arrow-left"></i> Tareas </a>
                      </div>
                      <div class="mb-2" class="fixed-top">
                          <a href="{% url 'tasks:create_nota' %}" class="btn btn-primary"><i class="bi bi-journal-arrow-up"></i> Calificar Tarea</a>
                      </div>
                    {% elif request.user.is_profesor %}
                    <div class="mb-2" class="fixed-top">
                      <a href="{% url 'tasks:tasks' %}" class="btn btn-secondary" role="button">
                        <i class="bi bi-box-arrow-left"></i> Tareas </a>
                    </div>
                    <div class="mb-2" class="fixed-top">
                        <a href="{% url 'tasks:create_nota' %}" class="btn btn-primary"><i class="bi bi-journal-arrow-up"></i> Calificar Tarea</a>
                    </div>
                    {% endif %}
                </span>
            </div>
        </div>


        <hr>
        {{ error }}

        <div class="row justify-content-md-center">
            <div class="col-6 p-4 border rounded shadow-lg" id="profile-box">
                <form method="POST" class="crispy" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success mb-2"><i class="bi bi-cloud-download"></i> Guardar</button>
                </form>
        
                <form action="{% url 'tasks:complete_task' task_id=task.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-info mb-2"><i class="bi bi-check-circle"></i> Completado</button>
                </form>
        
                <form action="{% url 'tasks:delete_task' task_id=task.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mb-2"><i class="bi bi-trash"></i> Eliminado</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

Learning/templates/Task/tasks.html
{% extends 'base.html' %}

{% block title %}
    Tareas
{% endblock  %}

{% block content %}
</div>
<br>
<div class="container my-4">
  <div class="row">
      <div class="col">
        <h1>Tareas Pendientes</h1>
      </div>
      <div class="col">
          <span class="float-end">
              {% if request.user.is_staff  %}
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'tasks:create_task' %}" class="btn btn-primary" role="button">
                    <i class="bi bi-plus-circle "></i> Agregar Tarea </a>
              </div>
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'tasks:task_completed' %}" class="btn btn-success" role="button">
                    <i class="bi bi-list-check"></i> Tareas Completadas </a>
              </div>
              {% elif request.user.is_profesor %}
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'tasks:create_task' %}" class="btn btn-primary" role="button">
                    <i class="bi bi-plus-circle "></i> Agregar Tarea </a>
              </div>
              <div class="mb-2" class="fixed-top">
                <a href="{% url 'tasks:task_completed' %}" class="btn btn-success" role="button">
                    <i class="bi bi-list-check"></i> Tareas Completadas </a>
              </div>
              {% endif %}
          </span>
      </div>
  </div>

  <hr>

  <!-- sección de mensajes -->
  {% if messages %}
      <div class="container mt-3">
          {% for message in messages %}
              <div class="alert alert-success" role="alert">
                  {{ message }}
              </div>
          {% endfor %}
      </div>
  {% endif %}

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 my-4">
        {% for task in tasks %}
          <div class="col">
              <div class="card">
                  <div class="card-body border rounded shadow-lg">
                      <h5 class="card-title">{{ task.title }}</h5>
                      <p class="card-text">{{ task.description }}</p>
                      <p class="card-text"><strong>Fecha de Completado: </strong><p> {{ task.datecompleted | date:'M j Y:i' }}</p>
                      </p>
                      <p class="card-text"><strong>Archivo Adjunto: </strong><p> <a href="" target="_blank">{{ task.field.name }}</a></p>
                      </p><p class="card-text"><strong>Curso de tarea: </strong><p> {{ task.curso }}</p>
                    </p>

                      {% if course.status == 'F' %}
                          <h5><span class="badge bg-danger w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-warning" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'P' %}
                          <h5><span
                              class="badge bg-warning text-dark w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if course.is_enrolled %}
                              <a class="btn btn-sm btn-warning" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% elif course.status == 'I' %}
                          <h5><span class="badge bg-success w-100">{{ course.get_status_display|upper }}</span>
                          </h5>
                          {% if request.user.is_Estudiante and not course.is_enrolled %}
                              <a class="btn btn-sm btn-success" href="">Anotarse</a>
                          {% elif course.is_enrolled %}
                              <a class="btn btn-sm btn-primary" href="{% url 'learning_overview' %}">Ir al Perfil</a>
                          {% endif %}
                      {% endif %}

                      {% if request.user.is_staff %}
                            <a class="btn btn-sm btn-warning" href="{% url 'tasks:task_detail' task_id=task.id %}">Editar</a>
                      {% elif request.user.is_profesor %}
                          <a class="btn btn-sm btn-warning" href="{% url 'tasks:task_detail' task_id=task.id %}">Editar</a>
                      {% endif %}
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>

{% endblock %}

Learning/templates/Task/tasks_completed.html
{% extends "base.html" %}
{% csrf_token %}
{% block content %}

<main class="container">
    <div class="container mt-4">
    <div class="row">
        <div class="col">
            <h1>Task</h1>
        </div>
        <div class="col">
            <span class="float-end">
                {% if request.user.is_staff %}
                <div class="mb-2" class="fixed-top">
                    <a href="{% url 'tasks:tasks' %}" class="btn btn-secondary" role="button">
                      <i class="bi bi-box-arrow-left"></i> Tareas </a>
                  </div>
                {% elif request.user.is_profesor %}
                <div class="mb-2" class="fixed-top">
                  <a href="{% url 'tasks:tasks' %}" class="btn btn-secondary" role="button">
                    <i class="bi bi-box-arrow-left"></i> Tareas </a>
                </div>
                {% endif %}
            </span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center display-3 py-5"></h1>
            <h4 style="color: chartreuse;">{{msg}} {{title}}</h4>
            <ul class="list-group">
                {% for tsk in tasks %}
                <a href="{% url 'tasks:task_detail' tsk.id %}" class="list-group-item">
                    <header class="d-flex justify-content-between" >
                        <li style="list-style:none">                                   
                            {% if tsk.important %}
                            <h4 class="fw-blod text-success">{{tsk.title}}</h4> 
                            <p>{{tsk.description}}</p>
                            <p style="color: red;">¡Importante!</p>
                            {% else %}
                            <h4>{{tsk.title}}</h4>
                            <p>{{tsk.description}}</p>
                            {% endif %}
                            <p>{{tsk.datecompleted|date:'M j Y:i'}}</p>
                        </li>
                        <li>
                            <p>{{tsk.user.username}}</p>
                        </li>
                    </header>
                    
                </a>
                {% endfor %}
            </ul>
        </div>
    </div>
</main>


{% endblock %}